# Generated by Django 3.0.3 on 2020-10-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201006_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
        ),
    ]
